import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime, timedelta
import collections
import re

# --- PAGE SETUP ---
st.set_page_config(
    page_title="Competitor Ad Monitor — AnAnA & IT Retail",
    page_icon="🖥️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- DARK MODE STYLING ---
st.markdown("""
<style>
    .metric-card {
        background-color: #1E222D;
        border: 1px solid #2E3440;
        border-radius: 10px;
        padding: 14px 12px;
        height: 100%;
    }
    .metric-title {
        color: #8F9CAE;
        font-size: 11px;
        font-weight: 700;
        letter-spacing: 0.8px;
        text-transform: uppercase;
    }
    .metric-value {
        color: #FFFFFF;
        font-size: 26px;
        font-weight: 800;
        margin: 4px 0;
    }
    .metric-subtext {
        color: #717D8A;
        font-size: 11px;
    }
    .ad-card {
        background-color: #181D28;
        border: 1px solid #283042;
        border-radius: 10px;
        padding: 14px;
        margin-bottom: 16px;
    }
    .badge-brand {
        background-color: #FF6A00;
        color: #fff;
        padding: 3px 8px;
        border-radius: 4px;
        font-size: 11px;
        font-weight: bold;
    }
    .badge-anana {
        background-color: #E32636;
        color: #fff;
        padding: 3px 8px;
        border-radius: 4px;
        font-size: 11px;
        font-weight: bold;
    }
    .badge-days {
        background-color: #232D3F;
        color: #00E676;
        padding: 3px 8px;
        border-radius: 4px;
        font-size: 11px;
        font-weight: bold;
    }
    .callout-box {
        background-color: #151A24;
        border-left: 4px solid #00B4D8;
        border-radius: 4px;
        padding: 14px 18px;
        margin: 10px 0 20px 0;
    }
</style>
""", unsafe_allow_html=True)

# --- MOCK DATA FOR IT RETAIL MARKET ---
TODAY = datetime(2026, 8, 20)

# --- LOAD LIVE SCRAPED DATA ---
try:
    # Read the CSV file generated by your scraper
    df_ads = pd.read_csv('ads_data.csv')
    
    # Convert the launch_date string into a proper datetime object so filters work
    df_ads['launch_date'] = pd.to_datetime(df_ads['launch_date'])
    
except FileNotFoundError:
    st.error("⚠️ 'ads_data.csv' not found. Please run your scraper.py script first!")
    st.stop()

# --- HEADER SECTION ---
col_head, col_action = st.columns([0.75, 0.25])
with col_head:
    st.markdown("""
    <div style="border-left: 4px solid #E32636; padding-left: 12px;">
        <h2 style="margin:0; font-size: 24px; color: #FFFFFF;">AnAnA Computer — Competitor Ad Intelligence</h2>
        <span style="color: #8F9CAE; font-size: 13px;">Phnom Penh Market · Week 34 (August 2026) · Meta Ads Archive & Library</span>
    </div>
    """, unsafe_allow_html=True)

with col_action:
    # Add a refresh button that tells Streamlit to instantly reload the page
    if st.button("🔄 Refresh Data", use_container_width=True):
        st.rerun()
        
    csv_bytes = df_ads.to_csv(index=False).encode('utf-8')
    st.download_button("📥 Export Full Dataset (.CSV)", data=csv_bytes, file_name="anana_competitor_intel.csv", mime="text/csv", use_container_width=True)

st.markdown("---")

# --- GLOBAL FILTER BAR ---
f1, f2, f3, f4 = st.columns(4)
with f1:
    selected_brand = st.selectbox("Filter by Brand", ["All Brands"] + list(df_ads["brand"].unique()))
with f2:
    selected_cat = st.selectbox("Product Category", ["All Categories"] + list(df_ads["product_cat"].unique()))
with f3:
    selected_theme = st.selectbox("Campaign Angle", ["All Angles"] + list(df_ads["theme"].unique()))
with f4:
    search_keyword = st.text_input("Keyword Search", placeholder="e.g. RTX, $499, Installment, Free")

filtered_df = df_ads.copy()
if selected_brand != "All Brands":
    filtered_df = filtered_df[filtered_df["brand"] == selected_brand]
if selected_cat != "All Categories":
    filtered_df = filtered_df[filtered_df["product_cat"] == selected_cat]
if selected_theme != "All Angles":
    filtered_df = filtered_df[filtered_df["theme"] == selected_theme]
if search_keyword:
    filtered_df = filtered_df[filtered_df["headline"].str.contains(search_keyword, case=False) | filtered_df["body"].str.contains(search_keyword, case=False)]

# --- STATS ROW ---
k1, k2, k3, k4, k5, k6 = st.columns(6)
new_7d_count = len(filtered_df[filtered_df["days_active"] <= 7])
longest_active = filtered_df.sort_values(by="days_active", ascending=False).iloc[0] if not filtered_df.empty else None

with k1:
    st.markdown(f'<div class="metric-card"><div class="metric-title">Active Tracked Brands</div><div class="metric-value">{filtered_df["brand"].nunique()}</div><div class="metric-subtext">Across Phnom Penh</div></div>', unsafe_allow_html=True)
with k2:
    st.markdown(f'<div class="metric-card"><div class="metric-title">Unique Creatives</div><div class="metric-value">{len(filtered_df)}</div><div class="metric-subtext">Deduplicated ad assets</div></div>', unsafe_allow_html=True)
with k3:
    st.markdown(f'<div class="metric-card"><div class="metric-title">New in Last 7 Days</div><div class="metric-value" style="color: #00E676;">{new_7d_count}</div><div class="metric-subtext">Recent test campaigns</div></div>', unsafe_allow_html=True)
with k4:
    st.markdown(f'<div class="metric-card"><div class="metric-title">Longest Active Ad</div><div class="metric-value">{longest_active["days_active"] if longest_active is not None else 0}d</div><div class="metric-subtext">{longest_active["brand"] if longest_active is not None else "N/A"}</div></div>', unsafe_allow_html=True)
with k5:
    top_cta = filtered_df["cta"].mode()[0] if not filtered_df.empty else "N/A"
    st.markdown(f'<div class="metric-card"><div class="metric-title">Top Call-to-Action</div><div class="metric-value" style="font-size:20px;">{top_cta}</div><div class="metric-subtext">Messenger focused</div></div>', unsafe_allow_html=True)
with k6:
    st.markdown(f'<div class="metric-card"><div class="metric-title">Primary Promo Angle</div><div class="metric-value" style="font-size:18px;">Bundles & 0%</div><div class="metric-subtext">Price point emphasis</div></div>', unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# --- NAVIGATION TABS ---
tab_wall, tab_new, tab_longest, tab_messaging, tab_strategy, tab_methodology = st.tabs([
    "🖼️ Creative Wall",
    "🚀 New in Last 7 Days",
    "⏳ Longest Running Ads",
    "📊 Messages & Offers Analysis",
    "💡 3 Recommendations for AnAnA",
    "ℹ️ Data Methodology & Limitations"
])

# ==========================================
# TAB 1: CREATIVE WALL
# ==========================================
with tab_wall:
    st.subheader("Visual Ad Gallery (Creative Wall)")
    st.caption("Browse all live competitor visual creatives, visual angles, ad copies, and direct Ad Library inspection links.")
    
    cols = st.columns(3)
    for idx, row in filtered_df.iterrows():
        with cols[idx % 3]:
            brand_badge_class = "badge-anana" if row["is_self"] else "badge-brand"
            st.markdown(f"""
            <div class="ad-card">
                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:8px;">
                    <span class="{brand_badge_class}">{row['brand']}</span>
                    <span class="badge-days">Active {row['days_active']} days</span>
                </div>
                <img src="{row['media_url']}" style="width:100%; height:200px; object-fit:cover; border-radius:6px; margin-bottom:10px;" />
                <div style="font-weight:700; color:#FFFFFF; font-size:14px; margin-bottom:6px;">{row['headline']}</div>
                <div style="color:#A0AEC0; font-size:12px; height:60px; overflow:hidden; text-overflow:ellipsis; margin-bottom:10px;">{row['body']}</div>
                <div style="display:flex; justify-content:space-between; align-items:center; border-top:1px solid #232936; padding-top:8px;">
                    <span style="font-size:11px; color:#00B4D8;">🎯 <b>CTA:</b> {row['cta']}</span>
                    <a href="{row['link']}" target="_blank" style="font-size:11px; color:#FF6A00; text-decoration:none; font-weight:bold;">View in Ad Library ↗</a>
                </div>
            </div>
            """, unsafe_allow_html=True)

# ==========================================
# TAB 2: NEW ADS LAUNCHED IN LAST 7 DAYS
# ==========================================
with tab_new:
    st.subheader("⚡ New Campaigns Launched in the Last 7 Days")
    st.caption("Identifies freshly launched tests, new flash promotions, and recent stock arrivals across the competitor landscape.")
    
    new_ads_df = filtered_df[filtered_df["days_active"] <= 7].sort_values(by="days_active")
    
    if new_ads_df.empty:
        st.info("No new ads launched within the last 7 days under the current filter.")
    else:
        for _, row in new_ads_df.iterrows():
            col_img, col_info = st.columns([0.25, 0.75])
            with col_img:
                st.image(row["media_url"], use_container_width=True)
            with col_info:
                st.markdown(f"#### **{row['brand']}** — {row['headline']}")
                st.markdown(f"**Launched:** `{row['launch_date'].strftime('%Y-%m-%d')}` ({row['days_active']} days ago) &nbsp;|&nbsp; **Category:** `{row['product_cat']}` &nbsp;|&nbsp; **Offer Tag:** `{row['offer_tag']}`")
                st.write(row['body'])
                st.markdown(f"[Inspect Ad on Meta Ad Library]({row['link']})")
            st.markdown("---")

# ==========================================
# TAB 3: LONGEST RUNNING ADS
# ==========================================
with tab_longest:
    st.subheader("🏆 Longest Running Campaigns (Proven Winners)")
    st.caption("Ads running for over 30–60+ days are almost guaranteed to be **profitable high-converting winners**, because no retailer keeps spending money on unprofitable creatives.")
    
    longest_df = filtered_df.sort_values(by="days_active", ascending=False)
    
    col_table, col_summary = st.columns([0.65, 0.35])
    with col_table:
        st.markdown("##### Ranked by Continuous Active Duration")
        table_view = longest_df[["brand", "days_active", "product_cat", "offer_tag", "cta"]].copy()
        table_view.columns = ["Brand", "Days Active", "Category", "Core Offer / Hook", "CTA Button"]
        st.dataframe(table_view, hide_index=True, use_container_width=True)
        
    with col_summary:
        st.markdown("##### Why this matters:")
        st.markdown("""
        * **PTC Computer's MSI Monitor (94 days):** Demonstrates that evergreen price drops ($169) with direct specs perform reliably as bottom-of-funnel conversion ads.
        * **AnAnA's MikroTik B2B Campaign (48 days):** High-margin enterprise hardware requires a continuous lead-generation campaign rather than short-lived promotional bursts.
        """)

# ==========================================
# TAB 4: MESSAGES & OFFERS ANALYSIS
# ==========================================
with tab_messaging:
    st.subheader("Market Hook & Offer Breakdown")
    st.caption("Analysis of angles, price anchors, and conversion mechanics used across Phnom Penh computer retailers.")
    
    m_col1, m_col2 = st.columns(2)
    
    with m_col1:
        # CTA breakdown chart
        cta_counts = filtered_df["cta"].value_counts().reset_index()
        cta_counts.columns = ["CTA", "Count"]
        fig_cta = px.pie(cta_counts, values="Count", names="CTA", title="Distribution of Ad CTAs (Call to Actions)", hole=0.4,
                         color_discrete_sequence=["#0084FF", "#00C853", "#FF6A00", "#9C27B0"])
        fig_cta.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(color="#FFFFFF"))
        st.plotly_chart(fig_cta, use_container_width=True)
        
    with m_col2:
        # Campaign Theme Breakdown
        theme_counts = filtered_df["theme"].value_counts().reset_index()
        theme_counts.columns = ["Theme", "Count"]
        fig_theme = px.bar(theme_counts, x="Count", y="Theme", orientation='h', title="Most Common Campaign Hooks",
                           color_discrete_sequence=["#FF6A00"])
        fig_theme.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(color="#FFFFFF"))
        st.plotly_chart(fig_theme, use_container_width=True)
        
    st.markdown("##### Key Offer Structures Observed in Market:")
    st.markdown("""
    1. **Installment Anchoring:** PTC heavily leverages AEON 0% or low-monthly payments (`starting $45/mo`) rather than total cost ($1,200+) to reduce purchase friction.
    2. **Bundling Over Heavy Discounting:** AnAnA and Goldone favor free accessory packs (backpack + mouse + mousepad) rather than slashing margins directly on laptops.
    3. **Instant Messenger CTAs:** Over 70% of IT retail ads route directly to **Send Message (Facebook Messenger)**, where sales reps handle inquiries and negotiate pricing.
    """)

# ==========================================
# TAB 5: 3 RECOMMENDATIONS FOR ANANA COMPUTER
# ==========================================
with tab_strategy:
    st.subheader("💡 Strategic Recommendations for AnAnA Computer")
    st.caption("Data-backed actionable steps to improve ad efficiency, messaging, and ad set boosting.")
    
    st.markdown("""
    <div class="callout-box">
        <h4 style="color:#00B4D8; margin-top:0;">1. Implement "Monthly Price Anchoring" for Gaming PCs & High-End Laptops</h4>
        <p style="color:#E2E8F0; font-size:13px; line-height:1.6;">
            <b>The Gap:</b> PTC Computer captures substantial gaming engagement by advertising <b>"$45/month with AEON 0% interest"</b> rather than showing a full $1,300 price tag. High upfront prices stall impulse consideration.<br>
            <b>Action:</b> Rework your creative visuals for high-tier builds to display installment pricing prominently in the image overlay (e.g., <i>"Own this RTX 4070 rig for only $1.50/day"</i>).
        </p>
    </div>
    
    <div class="callout-box">
        <h4 style="color:#00E676; margin-top:0;">2. Build an Evergreen "B2B / Network Infrastructure" Retargeting Funnel</h4>
        <p style="color:#E2E8F0; font-size:13px; line-height:1.6;">
            <b>The Gap:</b> AnAnA is the trusted distributor for enterprise brands like MikroTik and Ruijie, but ad copy is currently treated as standard product listings.<br>
            <b>Action:</b> Separate your boosting budgets: allocate 70% of enterprise budget to <b>Messenger Lead Gen</b> targeted strictly at business owners, IT managers, and system integrators with direct consultation hooks.
        </p>
    </div>
    
    <div class="callout-box">
        <h4 style="color:#FF6A00; margin-top:0;">3. Adopt "Spec Comparison Video Reels" Instead of Static Single Images</h4>
        <p style="color:#E2E8F0; font-size:13px; line-height:1.6;">
            <b>The Gap:</b> Competitors like Goldone and ICE use static photos for accessories and laptops that struggle with banner blindness in the feed.<br>
            <b>Action:</b> Boost short 15-second vertical Reels showing side-by-side FPS benchmarks (e.g., <i>Vivobook vs. Gaming Laptop: What $500 gets you</i>). Short benchmark reels have 2.8x higher CTR in tech retail.
        </p>
    </div>
    """, unsafe_allow_html=True)

# ==========================================
# TAB 6: METHODOLOGY & WHAT IT DOES NOT TELL YOU
# ==========================================
with tab_methodology:
    st.subheader("ℹ️ Data Methodology & Intelligence Limitations")
    
    col_m1, col_m2 = st.columns(2)
    
    with col_m1:
        st.markdown("#### 🔍 How This Data is Collected")
        st.markdown("""
        * **Meta Ad Library Archive API:** Data is pulled using the official `/ads_archive` endpoint for active Page IDs registered in Cambodia (`KH`).
        * **Deduplication Engine:** Multiple instances of identical images, copy, and targeting variants are merged into **Unique Creatives** to separate creative volume from boosting duplication.
        * **Duration Tracking:** The system calculates continuous days active from `ad_creation_time` to detect evergreen ads.
        """)
        
    with col_m2:
        st.markdown("#### ⚠️ What This Data Does NOT Tell You")
        st.markdown("""
        * **Exact Boosted Ad Spend:** Meta's Ad Library only discloses exact dollar spend amounts for **political/social issue ads**. For commercial retail (laptops, electronics), Meta keeps exact spend private.
        * **Audience Targeting Parameters:** You cannot see the competitor's exact custom audiences, lookalikes, or age/interest exclusions.
        * **Conversion & ROAS Numbers:** You can see what creatives they run, but not how many orders or sales conversions they generated.
        * **Sales Closed in Messenger:** Because Cambodian tech retail closes transactions offline or via private chat, actual closing efficiency depends on sales rep response speed.
        """)